In [7]:
# <Pandas 라이브러리: 1. Series>

# Series = Index가 붙은 값들의 한 줄(column)
# index = row의 이름표(label)

# ==================== Series 만들기 ====================
import pandas as pd

s = pd.Series([175, 180, 165, 170]) # List로 Series 만들기
print(s, "\n")

s = pd.Series([175, 180, 165, 170], index = ["철수", "영희", "민수", "지영"]) # index를 직접 지정하기
print(s)

# ==================== Series에서 값 꺼내기 ====================
print("\n")

print(s["영희"])
print(s.loc["영희"]) # 인덱스를 기준으로 값 찾기
print(s.iloc[1]) #숫자 위치를 기준으로 값 찾기
print(s.max()) # 최댓값
print(s.mean()) # 평균

0    175
1    180
2    165
3    170
dtype: int64

철수    175
영희    180
민수    165
지영    170
dtype: int64


180
180
180
180
172.5

In [8]:
# <Pandas 라이브러리: 2. DataFrame>

# DataFrame = row와 column이 있는 2차원 table
# └ row : 데이터 1건 (한 사람의 기록, 한 거래의 기록, 하루치의 기록ㆍㆍ)
# └ column : 속성(feature)
# └ index : 각 row의 이름표

# ==================== DataFrame 만들기 ====================

# DataFrame을 만드는 첫 단계: Dictionary를 이용해 데이터를 만들기 (key = 컬럼명, value = 그 컬럼의 데이터 리스트)

df = pd.DataFrame({
    "name" : ["철수", "영희", "민수", "지영"],
    "height" : [175, 180, 165, 170],
    "weight" : [70, 65, 58, 62]
})

print(df)
print("\n")
# ==================== Series와 DataFrame의 관계 (DataFrame의 Column은 Series이다!) ==================== 

# DataFrame = Series 여러 개를 옆으로 붙인 것
# 즉, DataFrame에서 Column 하나를 뽑으면 = Series

# column 하나 뽑기
col = df["height"]

print(col)
print("\n", type(col))
print("\n", type(df))

# 요약정리
df["height"].mean()
# ① df["height"]  → height 컬럼을 Series로 뽑고
# ② .mean()       → 그 Series의 평균을 구한다

  name  height  weight
0   철수     175      70
1   영희     180      65
2   민수     165      58
3   지영     170      62


0    175
1    180
2    165
3    170
Name: height, dtype: int64

 <class 'pandas.core.series.Series'>

 <class 'pandas.core.frame.DataFrame'>

np.float64(172.5)

In [9]:
# ==================== DataFrame에서 여러 column 뽑기 (대괄호의 의미) ==================== 
print("\n")
df["height"] # 대괄호 1개 = Series (1차원 데이터)
print("\n")
df[["height"]] # 대괄호 2개 = DataFrame (2차원 데이터, 컬럼 1개짜리 표)
print("\n")
df[["height", "weight"]] # 여러 컬럼 뽑기 => 무조건 DataFrame 형식으로 나옴

   height  weight
0     175      70
1     180      65
2     165      58
3     170      62

In [10]:
# ==================== DataFrame에서 column 다루기  ==================== 

# 1)  새 컬럼 만들기

df["bmi"] = df["weight"] / (df["height"] /100) ** 2
print(df)

# 2)  컬럼 이름 바꾸기

df = df.rename(columns={"bmi":"BMI"})

# 3)  컬럼 삭제하기

df = df.drop(columns=["BMI"])

# 4)  자료형 바꾸기

df["height"] = df["height"].astype(float)

# pd.to_numeric: 괄호 안에 있는 데이터를 숫자(정수나 실수) 타입으로 변환해줘
df["height"] = pd.to_numeric(df["height"], errors="coerce") # errors="coerce": 숫자로 바꿀 수 없는 이상한 문자(예-문자열)을 만나면, 에러 내지 말고 NaN으로 바꿔라.

# 문자열을 날짜 타입으로 변환해줘     (예"2025-01-15")
# df["date"] = pd.to_datetime(df["date"])

  name  height  weight        bmi
0   철수     175      70  22.857143
1   영희     180      65  20.061728
2   민수     165      58  21.303949
3   지영     170      62  21.453287

In [11]:
# ==================== DataFrame에서 row 다루기  ==================== 

# loc = 인덱스 이름(label) 기반 / iloc = 순서(정수 위치) 기반
# ※ 아직 index(row들의 이름) label을 정하지 않았기 때문에, default인 숫자 위치로 매겨져있음. 헷갈리지 않게 조심


# df.loc[ 행, 열 ]
df.loc[1] # index 이름표가 1인 행 => Series로 반환
df.loc[1, "name"] # 1행의 name 값 => "영희"
df.loc[0:2, ["height", "weight"]] # 0~2행(2행 포함), name과 height 컬럼 => DataFrame 형식으로 반환됨


# df.iloc[ 행, 열 ]
df.iloc[1] # 인덱스의 정수 위치가 1인 행  => Series로 반환
df.iloc[0:2] # 인덱스의 정수 위치가 0~1인 행 (***2행 미포함***)
df.iloc[0:2, 0:2] # 행 0~1, 열 0~1

  name  height
0   철수   175.0
1   영희   180.0

In [12]:
# <EDA : 데이터 불러오기 >


# 실전에서는 직접 DataFrame을 만들기보다, 파일을 읽어온다.
                    # df = pd.read_csv("data.csv")
                    # df = pd.read_excel("data.xlsx")
                    # df = pd.read_json("data.json")

# Data를 불러온 뒤, 무조건 하는 5가지
                    # df.head()         #위에서 5행 미리보기 - 데이터가 어떻게 생겼나
                   	# df.shape          # (행 수, 열 수) - 데이터 규모 확인
                    # df.info()         # 컬럼별 타입 + 결측치 개수
                    # df.describe()     # 수치형 컬럼의 통계 요약 (평균, 최솟값, 최댓값 등)
                    # df.isnull().sum() # 컬럼별 결측치 개수만 콕 집어 보기

In [14]:
# <조건 필터링 (불리언 인덱싱)>

# 1) 조건식을 쓰면 True/False Series가 나온다
cond = df["height"] >= 170  # 170 이상인 사람만 보기 - EDA 기술

# 2) 이 True/False를 df에 넣으면, True인 행만 남는다.    
print(df[cond])  # print(df[변수]) => series 형태로 출력 가능! // df["height"] => 컬럼을 series로 출력 // df[cond] => 변수에 할당된건 DataFrane으로 출력

print("\n==========================")



# ==================== 실전에서는 한 줄로 사용한다.====================
df[df["height"] >= 170]     
print("\n==========================")
df.loc[df["height"] >= 170, ["name"]]   # df.loc[행, 열]  

# ※ df[df["height"] >= 170] 등 이 구정들이 출력 안되는 이유:  print()에 넣지않으면 메모리에만 저장되고, 마지막 셀의 코드만 출력됨.



# ==================== 조건 여러 개 조합하기! ====================
print("\n==========================")

# and => &
# or => |   
# ※ and, or 등 각 조건은 반드시 괄호로 감싸기!

df[(df["height"] >= 170) & (df["weight"] < 70)]  # And
df[(df["height"] >= 180) | (df["weight"] < 60)]  # Or
df[~(df["height"] >= 170)]                       # Not      # df[~조건식] : 조건식에 만족하지 않으면 다 False!



# ==================== df.query() 메서드 사용하기 ====================

# df.query() : 판다스 DataFrame에서 Data를 필터링할 떄 사용.
# 데이터프레임에서 "내가 원하는 조건에 맞는 행(Row)만 쏙 골라내고 싶을 때" 사용
df.query("height >= 170 and weight < 70")    

# query 괄호 안에  1. and/or/not(논리 연산자 logical operators) 와    2. ==/!=/>=, <= (비교 연산자 Comparison Operators) 사용 가능



# ==================== 자주 쓰는 데이터 확인 메서드 ====================

df["name"].unique() # unique() : name 열의 고유값 목록을 반환      # 고유값 : '중복을 제거한 유일한 값'
df["name"].nunique() # nunique() : name 열의 고유값 개수를 반환
df["blood"].value_counts() # 각 값이 "몇 번씩 나왔는지 빈도수"를 세서 반환. 각 고유값의 개수(빈도)를 계산

  name  height  weight
0   철수   175.0      70
1   영희   180.0      65
3   지영   170.0      62

==========================

==========================

==========================

  name  height  weight
1   영희   180.0      65
3   지영   170.0      62

In [15]:
# <결측치(NaN) 다루기>

# 결측지를 그냥 두면 안 되는 이유: 머신러닝 모델 대부분이 NaN이 있으면 에러를 냄.
#                              그래서 반드시 1)찾고 => 2)지우거나 채워야 함.

# NaN (Not a Number): 값이 비어있음을 나타내는 표시.
#                     설문 무응답, 센서 오류, 데이터 누락 등으로 생기기도 함.

import numpy as np

df = pd.DataFrame({
    "name" : ["철수", "영희", "민수", "지영", "준호"],
    "height" : [175, 180, np.nan, 170, 168],
    "weight" : [70, np.nan, 58, 62, np.nan]
})
print(df)



# ==================== 결측치 찾기 ====================

# 입력된 데이터프레임과 동일한 형태(Shape)의 True/False로 이루어진 데이터프레임(Boolean Mask)을 결과로 반환

df.isnull()  # 전체 데이터프레임의 결측치 여부 확인 => 값이 비어 있으면(결측치이면) True, 값이 존재하면 False를 반환
df.isnull.sum() # 특정 열(Column)의 결측치 여부만 확인

# df.isna() = df.isnull()과 완전히 동일한 기능



# ==================== 결측치 제거 (dropna) ====================

# df.dropna() : 결측치가 포함된 줄(행/열)을 삭제하는 기능

# 핵심 파라미터
# 1) axis (방향) : 0 (기본값) => 결측치 있는 행(가로줄) 삭제 / 1 => 결측치 있는 열(세로줄) 삭제
# 2) how (기준) : how='any' (기본값) =>  결측치가 하나라도 있으면 삭제 / how='all' 모든 값이 전부 결측치여야 삭제
# 3) subset (타겟) : df.dropna(subset=['열이름']) => 지정한 특정 열의 결측치만 검사해서 삭제
# 4) thresh=N : 결측치가 있더라도,  유지시켜주는 옵션


df.dropna() # NaN이 하나라도 있는 "행" 삭제
df.dropna(subset=["height"]) # height가 NaN인 행만 삭제
df.dropna(axis=1) # NaN이 있는 "열" 삭제
df.dropna(how='all') # 모든 값이 결측치인 행만 삭제 
df.dropna(thresh=2) # 정상 데이터가 최소 2개 이상 있는 행만 남기고 삭제



# ==================== 결측치 채우기 (fillna) ====================

# df.fillna() : 결측치를 사용자가 지정한 값이나 데이터 기반의 값으로 채워넣는 메서드


# 핵심 파라미터

# 1) value : 대입하고자 하는 값(숫자, 문자, 통계값, 딕셔너리 등)을 지정하는 파라미터
#            └ 단일 고정값 예시 (value=0) : df["weight"] = df["weight"].fillna(0)
#            └ 계산된 통계값 예시 (value=계산식) : df["weight"] = df["weight"].fillna(df["weight"].mean())    # 평균값 대입
#                                              df["weight"] = df["weight"].fillna(df["weight"].median())  # 중앙값 대입
#                                              df["blood"]  = df["blood"].fillna(df["blood"].mode()[0])   # 최빈값 대입

# 2) method : 결측치를, 결측치 앞이나 뒤에 있는 정상 데이터로 채우는 방법
#            └ method='ffill' (직전 값) : df["price"].fillna(method='ffill')  /  df["price"] = df["price"].ffill()
#            └ method='bfill' (직후 값) : df["price"] = df["price"].bfill()  /  df["price"].fillna(method='bfill')

# 3) axis : method 파라미터를 사용할 때, 위아래 방향으로 값을 가져올지, 좌우 방향으로 가져올지 행/열 기준을 결정
#            └ axis=0 (기본값): 위쪽 행에 있는 값을 아래쪽 결측치에 대입   =>   df = df.ffill(axis=0)
#            └ axis=1 : 왼쪽 열에 있는 값을 오른쪽 결측치에 대입   =>   df = df.ffill(axis=1)

# 4) inplace : 메서드 실행 결과를 원본 데이터프레임 변수에 즉시 반영할지 여부를 결정하는 True/False 옵션
#            └ df["weight"].fillna(0, inplace=True)     # inplace=True: 원본에 바로 반영  /  inplace=False (기본값): 원본에 반영 안 함

  name  height  weight
0   철수   175.0    70.0
1   영희   180.0     NaN
2   민수     NaN    58.0
3   지영   170.0    62.0
4   준호   168.0     NaN

In [1]:
# < 이상치(outlier) 다루기 >

# 이상치 = 다른 값들에 비해 비정상적으로 크거나 작은 값.   평균을 왜곡시키고 모델 성능을 망침

# boxplot 으로 찾기 (*****chapter 4 끝내고*****)

In [4]:
# < 그룹별 데이터 분석 (Grouping) >

# 그룹화(Grouping) : 특정 열의 값이 같은 행들을 하나의 그룹으로 묶는 과정 => groupby() 함수 사용

# 그룹화 내부적 매커니즘: 분할(Split) => 적용(Apply) => 결합(Combination)

# Split: 기준 열에 따라 데이터를 그룹으로 분리  (지정한 컬럼의 고유값을 기준으로 전체 데이터프레임을 여러 개의 독립된 그룹으로 나눔)
# Apply: 각 개별 그룹에 독립적으로 함수 적용
#         └ 1) 집계(Aggregation) : 각 그룹을 대표하는 하나의 요약 통계량 산출 => 집계 함수: sum(), mean(), count(), min(), max(), median(), agg()
#         └ 2) 변환(Transformation) : DataFrame의 전체 형태(Shape)을 유지한 채로, 모든 행에 새로운 값을 계산 => 변환 함수 : transform
#         └ 3) 필터링(Filter) : 특정 조건을 만족하는 그룹 전체를 데이터 셋에서 통째로 유지하거나 제외시킴 => 필터링 함수 : filter()
# Combine: 연산된 결과를 하나의 데이터 구조로 통


import pandas as pd

# 데이터프레임 생성
data = {
    '부서' : ['영업', '기획', '영업', '기획', '영업'],
    '이름' : ['김철수', '이영', '박민수', '최지원', '홍길동'],
    '급여' : [300, 400, 350, 450, 280]
}
df = pd.DataFrame(data)

# [유형 1] 집계(Aggregation) : 부서별 평균 급여 구하기
# 결과로, 기준 열인 부서가 Index가 되고, 행이 2개로 줄어든 데이터프레임이 반환됨.
dept_mean = df.groupby('부서')['급여'].mean()
print(dept_mean)
print("\n")

# [유형 2] 변환(Transformation): 자신이 속한 부서의 평균 급여를 새 컬럼으로 추가
# 원본 데이터의 5개 행 구조를 그대로 유지한 채 값이 추가됨
df['부서평균급여'] = df.groupby('부서')['급여'].transform('mean')
print(df)
print("\n")

# [유형 3] 필터링(Filter): 전체 급여 합이 800이 넘는 부서의 데이터만 추출
# => 기획 부서의 총합은 850, 영업 부서는 930이므로, 둘 다 조건을 만족하기 때문에 전체 출력됨.
filtered_df = df.groupby('부서').filter(lambda x: x['급여'].sum() > 800)


# 전체 내부 계산 과정 플로우: https://share.gemini.google/xQBJ3vBUNQx3

부서
기획    425.0
영업    310.0
Name: 급여, dtype: float64


   부서   이름   급여  부서평균급여
0  영업  김철수  300   310.0
1  기획   이영  400   425.0
2  영업  박민수  350   310.0
3  기획  최지원  450   425.0
4  영업  홍길동  280   310.0